### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by skyfaller** [arussellsaw/news#1]
Thank you for the cool RSS reader!

Could you [add a license for your code to your repo](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository), to make it clear that people are welcome to contribute?

I personally prefer the AGPL. I agree with [Bruce Perens saying there are too many licenses](https://www.datamation.com/osrc/article.php/12068_3803101_2/Bruce-Perens-How-Many-Open-Source-Licenses-Do-You-Need.htm) creating license compatibility problems. That said, I'm ok with any license approved by the FSF + OSI. (Not that my opinion matters, since I'm just a random dude on the internet.)

**Comment by arussellsaw** [comment]
thank you for the AGPL suggestion, i've added that as the license! 🎉
