### ISSUE TITLE
Is it possible to enlarge supported languages ?

### ISSUE THREAD

**Issue by AboutRSS** [arussellsaw/news#5]
Hi. Thanks for the creation. Wondering whether it is possible that more languages could be supported.

**Comment by arussellsaw** [comment]
Hey! for sure I'd like to do something fully localised down the line. Right now though if you sign up you can add RSS feeds of any language, and specify categories in any language you like! I don't think there's much text on the site that isn't user provided, maybe just log in/search and settings buttons.
